meta_product_name: "Gasho"
meta_title: "Gasho -  We help you stretch"
meta_description: "Sport specialized stretch routines for you"
meta_image: "apple-icon-180x180.png" # should exist in `app/assets/images/`
twitter_account: "@Patricc21548784"   # required for Twitter Cards
